//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capybara_Stuff.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anime()
        {
            this.Comments = new HashSet<Comment>();
            this.EntityCategories = new HashSet<EntityCategory>();
            this.URLs = new HashSet<URL>();
            this.UserEntities = new HashSet<UserEntity>();
        }
    
        public int Id { get; set; }
        public string AnimeType { get; set; }
        public int GenreId { get; set; }
        public string Name_en { get; set; }
        public string Name_ru { get; set; }
        public string Description { get; set; }
        public int SeriesCount { get; set; }
        public int SerieDuration { get; set; }
        public Nullable<int> TotalDuration { get; set; }
        public int Year { get; set; }
        public int StudioId { get; set; }
    
        public virtual AnimeType AnimeType1 { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Studio Studio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityCategory> EntityCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<URL> URLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserEntity> UserEntities { get; set; }
    }
}
