//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capybara_Stuff.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CapyStuffEntities : DbContext
    {
        public CapyStuffEntities()
            : base("name=CapyStuffEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anime> Animes { get; set; }
        public virtual DbSet<AnimeType> AnimeTypes { get; set; }
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<DeathReason> DeathReasons { get; set; }
        public virtual DbSet<EntityCategory> EntityCategories { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<Profession> Professions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Series> Series { get; set; }
        public virtual DbSet<Status> Statuses { get; set; }
        public virtual DbSet<Studio> Studios { get; set; }
        public virtual DbSet<URL> URLs { get; set; }
        public virtual DbSet<UserEntity> UserEntities { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
